.apt_generated/com/github/adminfaces/starter/model/Despesa_.java
package com.github.adminfaces.starter.model;

import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Despesa.class)
public abstract class Despesa_ {

	public static volatile SingularAttribute<Despesa, Tipo> tipo;
	public static volatile SingularAttribute<Despesa, String> cnes;
	public static volatile SingularAttribute<Despesa, Double> valor;
	public static volatile SingularAttribute<Despesa, Integer> id;
	public static volatile SingularAttribute<Despesa, Integer> version;
	public static volatile SingularAttribute<Despesa, String> competencia;

}

.apt_generated/com/github/adminfaces/starter/model/Tipo_.java
package com.github.adminfaces.starter.model;

import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Tipo.class)
public abstract class Tipo_ {

	public static volatile SingularAttribute<Tipo, String> name;
	public static volatile SingularAttribute<Tipo, Integer> id;
	public static volatile SingularAttribute<Tipo, Integer> version;

}

src/main/java/com/github/adminfaces/starter/bean/DespesaFormMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.adminfaces.starter.bean;

import java.io.IOException;
import java.io.Serializable;

import javax.inject.Named;

import org.omnifaces.cdi.ViewScoped;
import org.omnifaces.util.Faces;

import com.github.adminfaces.persistence.bean.BeanService;
import com.github.adminfaces.persistence.bean.CrudMB;
import com.github.adminfaces.starter.model.Despesa;
import com.github.adminfaces.starter.service.DespesaService;

/**
 * @author rmpestano
 */
@Named
@ViewScoped
@BeanService(DespesaService.class)//use annotation instead of setter
public class DespesaFormMB extends CrudMB<Despesa> implements Serializable {


    public void afterRemove() {
        try {
            addDetailMsg("Despesa " + entity.getCnes()
                    + " removido com sucesso.");
            Faces.redirect("despesa-list.xhtml");
            clear(); 
            sessionFilter.clear(DespesaListMB.class.getName());//removes filter saved in session for DespesaListMB.
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void afterInsert() {
         addDetailMsg("Despesa " + entity.getCnes() + " cadastrado com sucesso.");
    }

    @Override
    public void afterUpdate() {
        addDetailMsg("Despesa " + entity.getCnes() + " updated successfully");
    }
    

}

src/main/java/com/github/adminfaces/starter/bean/DespesaListMB.java
package com.github.adminfaces.starter.bean;

import static com.github.adminfaces.persistence.util.Messages.addDetailMessage;
import static com.github.adminfaces.persistence.util.Messages.getMessage;
import static com.github.adminfaces.template.util.Assert.has;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.omnifaces.cdi.ViewScoped;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

import com.github.adminfaces.persistence.bean.CrudMB;
import com.github.adminfaces.persistence.model.Filter;
import com.github.adminfaces.persistence.service.CrudService;
import com.github.adminfaces.persistence.service.Service;
import com.github.adminfaces.starter.model.Despesa;
import com.github.adminfaces.starter.model.Tipo;
import com.github.adminfaces.starter.service.DespesaService;
import com.github.adminfaces.starter.service.TipoService;
import com.github.adminfaces.template.exception.BusinessException;

/**
 * Created by rmpestano on 12/02/17.
 */
@Named
@ViewScoped
public class DespesaListMB extends CrudMB<Despesa> implements Serializable {

	@Inject
	DespesaService despesaService;
	
	@Inject
	private TipoService tipoService;

	@Inject
	@Service
	CrudService<Despesa, Integer> crudService; // generic injection

	private UploadedFile file;

	@Inject
	public void initService() {
		setCrudService(despesaService);
	}
	
	@Override
	protected Filter<Despesa> initFilter() {
		Filter<Despesa> filter = super.initFilter();
		filter.getEntity().setTipo(new Tipo());
		return filter;
	}

	public void handleFileUpload(FileUploadEvent event) {
		try {
			Scanner scanner = new Scanner(event.getFile().getInputstream());
			Scanner dataScanner = null;
			int index = 0;
			List<Despesa> despList = new ArrayList<>();
			
			while (scanner.hasNextLine()) {
				dataScanner = new Scanner(scanner.nextLine());
				dataScanner.useDelimiter(";");
				Despesa desp = new Despesa();

				while (dataScanner.hasNext()) {
					String data = dataScanner.next();
					if (index == 0)
						desp.setCompetencia(new SimpleDateFormat("MM/yyyy").format(new SimpleDateFormat("yyyyMM").parse(data)));
					else if (index == 1)
						desp.setCnes(data);
					else if (index == 2) {
						Tipo tipo = null;
						try {
							tipo = tipoService.findByNome(data);
						} catch (Exception e) {
						}
						if (tipo == null) {
							tipo = new Tipo();
							tipo.setName(data);
							try {
								tipoService.saveOrUpdate(tipo);
							} catch (Exception e) {
								// TODO: handle exception
								continue;
							}
							if (tipo.getId() == null) {
								continue;
							}
							desp.setTipo(tipo);
						}
					}
					else if (index == 3)
						desp.setValor(new DecimalFormat("###,###,##0.00").parse(data).doubleValue());
					else
						System.out.println("invalid data::" + data);
					index++;
				}
				index = 0;
				despList.add(desp);
			}
			scanner.close();
			despesaService.insert(despList);
			FacesMessage msg = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
			FacesContext.getCurrentInstance().addMessage(null, msg);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	public List<String> completeCnes(String query) {
		List<String> result = despesaService.getCness(query);
		return result;
	}

	public void findDespesaById(Integer id) {
		if (id == null) {
			throw new BusinessException("Provide Despesa ID to load");
		}
		Despesa despesaFound = crudService.findById(id);
		if (despesaFound == null) {
			throw new BusinessException(String.format("No despesa found with id %s", id));
		}
		selectionList.add(despesaFound);
		getFilter().addParam("id", id);
	}

	public void delete() {
		int numDespesas = 0;
		for (Despesa selectedDespesa : selectionList) {
			numDespesas++;
			despesaService.remove(selectedDespesa);
		}
		selectionList.clear();
		addDetailMessage(numDespesas + " despesas deleted successfully!");
		clear();
	}

	public String getSearchCriteria() {
		StringBuilder sb = new StringBuilder(21);

		String competenciaParam = null;
		Despesa despesaFilter = filter.getEntity();

		Integer idParam = null;
		if (filter.hasParam("id")) {
			idParam = filter.getIntParam("id");
		}

		if (has(idParam)) {
			sb.append("<b>id</b>: ").append(idParam).append(", ");
		}

		if (filter.hasParam("competencia")) {
			competenciaParam = filter.getStringParam("competencia");
		} else if (has(despesaFilter) && despesaFilter.getCompetencia() != null) {
			competenciaParam = despesaFilter.getCompetencia();
		}

		if (has(competenciaParam)) {
			sb.append("<b>competencia</b>: ").append(competenciaParam).append(", ");
		}

		String cnesParam = null;
		if (filter.hasParam("cnes")) {
			cnesParam = filter.getStringParam("cnes");
		} else if (has(despesaFilter) && despesaFilter.getCnes() != null) {
			cnesParam = despesaFilter.getCnes();
		}

		if (has(cnesParam)) {
			sb.append("<b>cnes</b>: ").append(cnesParam).append(", ");
		}

		Double valorParam = null;
		if (filter.hasParam("valor")) {
			valorParam = filter.getDoubleParam("valor");
		} else if (has(despesaFilter) && despesaFilter.getCnes() != null) {
			valorParam = despesaFilter.getValor();
		}

		if (has(valorParam)) {
			sb.append("<b>valor</b>: ").append(valorParam).append(", ");
		}

		if (filter.hasParam("minValor")) {
			sb.append("<b>").append(getMessage("label.minValor")).append("</b>: ").append(filter.getParam("minValor")).append(", ");
		}

		if (filter.hasParam("maxValor")) {
			sb.append("<b>").append(getMessage("label.maxValor")).append("</b>: ").append(filter.getParam("maxValor")).append(", ");
		}

		int commaIndex = sb.lastIndexOf(",");

		if (commaIndex != -1) {
			sb.deleteCharAt(commaIndex);
		}

		if (sb.toString().trim().isEmpty()) {
			return "No search criteria";
		}

		return sb.toString();
	}

	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

}

src/main/java/com/github/adminfaces/starter/bean/Lists.java
package com.github.adminfaces.starter.bean;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.inject.Named;

import com.github.adminfaces.persistence.service.CrudService;
import com.github.adminfaces.persistence.service.Service;
import com.github.adminfaces.starter.model.Despesa;
import com.github.adminfaces.starter.model.Despesa_;
import com.github.adminfaces.starter.model.Tipo;
import com.github.adminfaces.starter.service.TipoService;

@ApplicationScoped
public class Lists implements Serializable {

	@Inject
	@Service
	private CrudService<Despesa, Integer> crudService;

	@Inject
	private TipoService tipoService;

	@Produces
	@Named("cnes")
	public List<String> cnes() {
		return crudService.criteria().select(String.class, crudService.attribute(Despesa_.cnes)).getResultList();
	}

	@Produces
	@Named("tipos")
	public List<Tipo> tipos() {
		return tipoService.criteria().getResultList();
	}
}

src/main/java/com/github/adminfaces/starter/bean/TipoFormMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.adminfaces.starter.bean;

import java.io.IOException;
import java.io.Serializable;

import javax.inject.Named;

import org.omnifaces.cdi.ViewScoped;
import org.omnifaces.util.Faces;

import com.github.adminfaces.persistence.bean.BeanService;
import com.github.adminfaces.persistence.bean.CrudMB;
import com.github.adminfaces.starter.model.Tipo;
import com.github.adminfaces.starter.service.TipoService;

/**
 * @author rmpestano
 */
@Named
@ViewScoped
@BeanService(TipoService.class) // use annotation instead of setter
public class TipoFormMB extends CrudMB<Tipo> implements Serializable {

	public void afterRemove() {
		try {
			addDetailMsg("Tipo " + entity.getName() + " removido com sucesso.");
			Faces.redirect("tipo-list.xhtml");
			clear();
			sessionFilter.clear(TipoListMB.class.getName());// removes filter saved in session for TipoListMB.

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@Override
	public void afterInsert() {
		addDetailMsg("Tipo " + entity.getName() + " cadastrado com sucesso.");
	}

	@Override
	public void afterUpdate() {
		addDetailMsg("Tipo " + entity.getName() + " updated successfully");
	}

}

src/main/java/com/github/adminfaces/starter/bean/TipoListMB.java
package com.github.adminfaces.starter.bean;

import static com.github.adminfaces.persistence.util.Messages.addDetailMessage;
import static com.github.adminfaces.template.util.Assert.has;

import java.io.Serializable;

import javax.inject.Inject;
import javax.inject.Named;

import org.omnifaces.cdi.ViewScoped;

import com.github.adminfaces.persistence.bean.CrudMB;
import com.github.adminfaces.persistence.service.CrudService;
import com.github.adminfaces.persistence.service.Service;
import com.github.adminfaces.starter.model.Tipo;
import com.github.adminfaces.starter.service.TipoService;
import com.github.adminfaces.template.exception.BusinessException;

/**
 * Created by rmpestano on 12/02/17.
 */
@Named
@ViewScoped
public class TipoListMB extends CrudMB<Tipo> implements Serializable {

	@Inject
	TipoService tipoService;

	@Inject
	@Service
	CrudService<Tipo, Integer> crudService; // generic injection

	@Inject
	public void initService() {
		setCrudService(tipoService);
	}

	public void findTipoById(Integer id) {
		if (id == null) {
			throw new BusinessException("Provide Tipo ID to load");
		}
		Tipo tipoFound = crudService.findById(id);
		if (tipoFound == null) {
			throw new BusinessException(String.format("No tipo found with id %s", id));
		}
		selectionList.add(tipoFound);
		getFilter().addParam("id", id);
	}

	public void delete() {
		int numTipos = 0;
		for (Tipo selectedTipo : selectionList) {
			numTipos++;
			tipoService.remove(selectedTipo);
		}
		selectionList.clear();
		addDetailMessage(numTipos + " tipos deleted successfully!");
		clear();
	}

	public String getSearchCriteria() {
		StringBuilder sb = new StringBuilder(21);

		String nameParam = null;
		Tipo tipoFilter = filter.getEntity();

		Integer idParam = null;
		if (filter.hasParam("id")) {
			idParam = filter.getIntParam("id");
		}

		if (has(idParam)) {
			sb.append("<b>id</b>: ").append(idParam).append(", ");
		}

		if (filter.hasParam("name")) {
			nameParam = filter.getStringParam("name");
		} else if (has(tipoFilter) && tipoFilter.getName() != null) {
			nameParam = tipoFilter.getName();
		}

		if (has(nameParam)) {
			sb.append("<b>name</b>: ").append(nameParam).append(", ");
		}

		int commaIndex = sb.lastIndexOf(",");

		if (commaIndex != -1) {
			sb.deleteCharAt(commaIndex);
		}

		if (sb.toString().trim().isEmpty()) {
			return "No search criteria";
		}

		return sb.toString();
	}

}

src/main/java/com/github/adminfaces/starter/model/Tipo.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.adminfaces.starter.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.github.adminfaces.persistence.model.BaseEntity;

/**
 * @author rmpestano
 */
@Entity
@Table(name = "tipo")
public class Tipo extends BaseEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	@Column(name = "name")
	private String name;

	@Version
	private Integer version;

	public Tipo() {
	}

	public Tipo(Integer id) {
		this.id = id;
	}

	@Override
	public Integer getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Tipo name(String name) {
		this.name = name;
		return this;
	}

	public boolean hasName() {
		return name != null && !"".equals(name.trim());
	}
}

src/main/java/com/github/adminfaces/starter/infra/security/LogonMB.java
package com.github.adminfaces.starter.infra.security;

import static com.github.adminfaces.persistence.util.Messages.addDetailMessage;

import java.io.IOException;
import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Specializes;
import javax.inject.Named;

import org.omnifaces.util.Faces;

import com.github.adminfaces.template.session.AdminSession;


/**
 * Created by rmpestano on 12/20/14.
 *
 * This is just a login example.
 *
 * AdminSession uses isLoggedIn to determine if user must be redirect to login page or not.
 * By default AdminSession isLoggedIn always resolves to true so it will not try to redirect user.
 *
 * If you already have your authorization mechanism which controls when user must be redirect to initial page or logon
 * you can skip this class.
 */
@Named
@SessionScoped
@Specializes
public class LogonMB extends AdminSession implements Serializable {

    private String currentUser;
    private String email;
    private String password;
    private boolean remember;


    public void login() throws IOException {
        currentUser = email;
        addDetailMessage("Bem vindo <b>" + email + "</b>");
        Faces.getExternalContext().getFlash().setKeepMessages(true);
        Faces.redirect("index.xhtml");
    }

    @Override
    public boolean isLoggedIn() {

        return currentUser != null;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isRemember() {
        return remember;
    }

    public void setRemember(boolean remember) {
        this.remember = remember;
    }

    public String getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
    }
}

src/main/webapp/despesa-list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:adm="http://github.com/adminfaces"
                template="#{layoutMB.template}">

    <ui:define name="head-end">
        <style type="text/css">
            .ui-datatable .ui-datatable-header {
                text-align: right !important;
            }

            th.ui-filter-column {
                padding: 5px 2px !important;
            }

            #footer:hover {
                opacity: .7;
            }

            #footer {
                float: right;
                font-size: 12px;
                color: #3c8dbc;
                font-weight: 500;
            }
            
            .ui-datatable-footer {
                border: none;
            }

        </style>
    </ui:define>
  
  
  <ui:define name="body-begin">
        <ui:param name="title" value="Informações de Despesas"/> <!-- Automatic create breadCrumb and page title when param 'title' is provided. --> 
    </ui:define>

    <ui:define name="description">
        Tabela de gastos
    </ui:define>

    <ui:define name="body">

        <h:form>
            <div class="box box-primary">
                <div class="box-header with-border">
                    <div id="main-buttons" class="hidden-sm hidden-xs">
                        <p:commandButton action="despesa-form?faces-redirect=true" icon="fa fa-plus"
                                         value="Novo" styleClass="btn-primary"/>
                        <p:spacer width="5"/>
                        <p:commandButton value="Remover Selecionado" icon="fa fa-trash" styleClass="btn-danger"
                                         action="#{despesaListMB.delete}"
                                         disabled="#{empty despesaListMB.selectionList or despesaListMB.selectionList.size() == 0}"
                                         process="@this" update="@form"
                        >
                            <p:confirm header="Confirmação" message="Confirma a operação??" icon="ui-icon-danger"/>
                        </p:commandButton>
                        <p:spacer width="5"/>
                        <p:commandButton value="Busca" update="@(.ui-dialog)" styleClass="btn-info"
                                         oncomplete="PF('searchDialog').show()" icon="fa fa-search"/>

                        <p:spacer width="5"/>
                        <p:commandButton value="Limpar" update="@(.ui-dialog, .ui-datatable)" process="@form"
                                         action="#{despesaListMB.clear}"
                                         icon="fa fa-refresh"/>
                    </div>

                    <p:splitButton value="Novo" action="despesa-form?faces-redirect=true"
                                   icon="fa fa-plus"
                                   styleClass="hidden-md hidden-lg btn-primary">
                        <p:menuitem value="Remover Selecionado" action="#{despesaListMB.delete}"
                                    process="@this" update="@form"
                                    disabled="#{empty despesaListMB.selectionList or despesaListMB.selectionList.size() == 0}"
                                    icon="fa fa-trash">
                            <p:confirm header="Confirmação" message="Confirma a operação??" icon="ui-icon-danger"/>
                        </p:menuitem>
                        <p:menuitem value="Busca" update="@(.ui-dialog)"
                                    oncomplete="PF('searchDialog').show()"
                                    icon="fa fa-search"/>

                        <p:menuitem value="Limpar" update="@(.ui-dialog, .ui-datatable)" process="@form"
                                    action="#{despesaListMB.clear}"
                                    icon="fa fa-refresh"/>
                    </p:splitButton>

                    <p:separator/>
                    <p:dataTable id="despesasTable" widgetVar="despesasTable" var="c" value="#{despesaListMB.list}" rows="10"
                                 rowKey="#{c.id}" lazy="true" paginator="true"
                                 filteredValue="#{despesaListMB.filteredValue}"
                                 paginatorPosition="bottom" selection="#{despesaListMB.selectionList}"
                                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {JumpToPageDropdown}"
                                 currentPageReportTemplate="[ {startRecord} to {endRecord} of {totalRecords} ]"
                                 rowsPerPageTemplate="5,10,15,20,30"
                    >

                        <p:ajax event="rowSelectCheckbox" update="@(.ui-button, .ui-confirm-dialog)"/>
                        <p:ajax event="rowUnselectCheckbox" update="@(.ui-button, .ui-confirm-dialog)"/>
                        <p:ajax event="rowSelect" update="@(.ui-button, .ui-confirm-dialog)"/>
                        <p:ajax event="rowUnselect" update="@(.ui-button, .ui-confirm-dialog)"/>

                        <p:column selectionMode="multiple" width="5%" styleClass="align-center"/>

                        <p:column headerText="CNES" filterBy="#{c.cnes}" sortBy="#{c.cnes}"
                                  filterMatchMode="contains">
                            <f:facet name="filter">
                                <p:autoComplete value="#{despesaListMB.filter.entity.cnes}" forceSelection="true"
                                                minQueryLength="2" queryDelay="500" dropdown="true"
                                                completeMethod="#{despesaListMB.completeCnes}" maxResults="10">
                                    <p:ajax event="itemSelect" process="@this" update="@none"
                                            oncomplete="PF('despesasTable').filter()"/>
                                </p:autoComplete>
                            </f:facet>
                            <p:link value="#{c.cnes}" outcome="despesa-form.xhtml">
                                <f:param name="id" value="#{c.id}"/>
                            </p:link>

                        </p:column>
                        <p:column headerText="Tipo" sortBy="#{c.tipo.name}" filterBy="#{c.tipo.name}">
                            <f:facet name="filter">
                                <p:inputText value="#{despesaListMB.filter.entity.tipo.name}">
                                    <p:ajax process="@this" update="@none" oncomplete="PF('despesasTable').filter()"/>
                                </p:inputText>
                            </f:facet>
                            #{c.tipo.name}
                        </p:column>
                        <p:column headerText="Competência" sortBy="#{c.competencia}" filterBy="#{c.competencia}">
                            <f:facet name="filter">
                                <p:inputText value="#{despesaListMB.filter.entity.competencia}">
                                    <p:ajax process="@this" update="@none" oncomplete="PF('despesasTable').filter()"/>
                                </p:inputText>
                            </f:facet>
                            #{c.competencia}
                        </p:column>
                        <p:column headerText="Valor" sortBy="#{c.valor}" filterBy="#{c.valor}">
                            <f:facet name="filter">
                                <p:spinner value="#{despesaListMB.filter.entity.valor}">
                                    <f:converter converterId="javax.faces.Double"/>
                                    <p:ajax process="@this" update="@none" oncomplete="PF('despesasTable').filter()"/>
                                </p:spinner>
                            </f:facet>
                            #{c.valor}
                        </p:column>
                        <f:facet name="footer">
                            <div id="footer">
                                Filtros <i class="fa fa-filter"/>
                            </div>
                        </f:facet>
                    </p:dataTable>
                    <br/>
                    <p:fileUpload value="#{despesaListMB.file}" styleClass="btn-primary" auto="true" label="Carregar Arquivo" fileUploadListener="#{despesaListMB.handleFileUpload}"
                        	sizeLimit="100000" allowTypes="/(\.|\/)(csv|xls)$/" update="despesasTable"/>
                </div>
            </div>
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" styleClass="box-solid box-danger">
                <p:commandButton value="Sim" type="button" styleClass="btn-material btn-primary ui-confirmdialog-yes"
                                 icon="fa fa-check"/>
                <p:commandButton value="Não" type="button" styleClass="btn-material btn-danger ui-confirmdialog-no"
                                 icon="fa fa-close"/>
            </p:confirmDialog>
        </h:form>


        <p:dialog header="Busca despesas" widgetVar="searchDialog" height="400" modal="true" appendTo="@(body)"
                  width="500" responsive="true" draggable="false" styleClass="box-success">

            <h:form>
                <p:commandButton value="OK" update="@form @(.ui-datatable, .ui-tooltip)" icon="fa fa-check"
                                 ignoreAutoUpdate="true" styleClass="btn-primary"/>
                <p:spacer height="5"/>
                <p:commandButton value="Limpar" action="#{despesaListMB.clear}" process="@this"
                                 update="@form @(.ui-datatable, .ui-tooltip)" styleClass="btn-success"
                                 icon="fa fa-refresh"/>
                <p:spacer height="5"/>
                <p:commandButton value="Fechar" icon="fa fa-close" oncomplete="PF('searchDialog').hide()"/>
                <p:separator/>

                <div class="ui-g ui-fluid">
                    <div class="ui-g-12">
                        <p:outputLabel for="cnes" value="CNES"/>
                    </div>
                    <div class="ui-g-12">
                        <p:selectOneMenu id="cnes" value="#{despesaListMB.filter.entity.cnes}">
                            <f:selectItem itemLabel="..." itemValue=""/>
                            <f:selectItems value="#{cnes}" var="m" itemLabel="#{m}"
                                           itemValue="#{m}"/>
                        </p:selectOneMenu>
                    </div>
                    <div class="ui-g-12">
                        <p:outputLabel for="competencia" value="Competência"/>
                    </div>
                    <div class="ui-g-12">
                        <p:inputMask mask="99/9999" id="competencia" value="#{despesaListMB.filter.entity.competencia}"/>
                    </div>

                    <div class="ui-g-6 ui-sm-12 ui-g-nopad">
                        <div class="ui-g-12">
                            <p:outputLabel for="min" value="Valor Min."/>
                        </div>
                        <div class="ui-g-12">
                            <p:inputNumber id="min" value="#{despesaListMB.filter.params.minValor}"/>
                        </div>
                    </div>

                    <div class="ui-g-6 ui-sm-12 ui-g-nopad">
                        <div class="ui-g-12">
                            <p:outputLabel for="max" value="Valor Max."/>
                        </div>
                        <div class="ui-g-12">
                            <p:inputNumber id="max" value="#{despesaListMB.filter.params.maxValor}"/>
                        </div>
                    </div>
                </div>
            </h:form>
        </p:dialog>

        <p:outputPanel autoUpdate="true">
            <p:tooltip for="@(div[id$=footer])" escape="false" position="top"
                       showEvent="mouseover" hideEvent="mouseleave"
                       value="#{despesaListMB.searchCriteria}"/>
        </p:outputPanel>

    </ui:define>

</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="#{layoutMB.template}">

    <ui:define name="head-end">
        <ui:param name="renderBreadCrumb" value="false"/>
    </ui:define>

    <ui:define name="title">
    </ui:define>

</ui:composition>